// constants/indianRecipes.ts
// Curated Indian meal presets mapped to BioGears nutritional parameters

export type MealType = 'balanced' | 'high_carb' | 'high_protein' | 'fast_food' | 'ketogenic';

export interface IndianRecipe {
  id: string;
  name: string;
  emoji: string;
  calories: number;
  meal_type: MealType;
  category: 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'beverage';
  description?: string;
  // Optional custom macros (g) — used when meal_type === 'custom'
  carb_g?: number;
  fat_g?: number;
  protein_g?: number;
}

export const INDIAN_RECIPES: IndianRecipe[] = [
  // ── BREAKFAST ──────────────────────────────────────────────
  {
    id: 'idli_2',
    name: 'Idli (2 pieces)',
    emoji: '🫓',
    calories: 140,
    meal_type: 'balanced',
    category: 'breakfast',
    description: 'Steamed rice cakes with sambar',
    carb_g: 30, fat_g: 1, protein_g: 5,
  },
  {
    id: 'dosa',
    name: 'Masala Dosa',
    emoji: '🥞',
    calories: 280,
    meal_type: 'high_carb',
    category: 'breakfast',
    description: 'Crispy rice crepe with potato filling',
    carb_g: 45, fat_g: 8, protein_g: 6,
  },
  {
    id: 'poha',
    name: 'Poha',
    emoji: '🍚',
    calories: 250,
    meal_type: 'balanced',
    category: 'breakfast',
    description: 'Flattened rice with vegetables and spices',
    carb_g: 40, fat_g: 6, protein_g: 5,
  },
  {
    id: 'upma',
    name: 'Upma',
    emoji: '🫕',
    calories: 200,
    meal_type: 'balanced',
    category: 'breakfast',
    description: 'Semolina porridge with vegetables',
    carb_g: 30, fat_g: 5, protein_g: 5,
  },
  {
    id: 'paratha_2',
    name: 'Aloo Paratha (2)',
    emoji: '🫓',
    calories: 420,
    meal_type: 'balanced',
    category: 'breakfast',
    description: 'Stuffed whole wheat flatbread with butter',
    carb_g: 55, fat_g: 16, protein_g: 9,
  },
  {
    id: 'puri_bhaji',
    name: 'Puri Bhaji',
    emoji: '🍽️',
    calories: 500,
    meal_type: 'fast_food',
    category: 'breakfast',
    description: 'Deep-fried bread with potato curry',
    carb_g: 65, fat_g: 20, protein_g: 8,
  },
  {
    id: 'chila',
    name: 'Besan Chila',
    emoji: '🥗',
    calories: 180,
    meal_type: 'high_protein',
    category: 'breakfast',
    description: 'Chickpea flour pancake',
    carb_g: 22, fat_g: 5, protein_g: 10,
  },
  // ── LUNCH ──────────────────────────────────────────────────
  {
    id: 'dal_rice',
    name: 'Dal Rice',
    emoji: '🍛',
    calories: 520,
    meal_type: 'balanced',
    category: 'lunch',
    description: 'Lentil soup with steamed rice',
    carb_g: 85, fat_g: 8, protein_g: 18,
  },
  {
    id: 'roti_sabzi',
    name: 'Roti + Sabzi (2 rotis)',
    emoji: '🍽️',
    calories: 480,
    meal_type: 'balanced',
    category: 'lunch',
    description: 'Whole wheat roti with vegetable curry',
    carb_g: 70, fat_g: 12, protein_g: 12,
  },
  {
    id: 'rajma_chawal',
    name: 'Rajma Chawal',
    emoji: '🫘',
    calories: 600,
    meal_type: 'high_protein',
    category: 'lunch',
    description: 'Kidney bean curry with rice',
    carb_g: 90, fat_g: 10, protein_g: 22,
  },
  {
    id: 'chole_bhature',
    name: 'Chole Bhature',
    emoji: '🍛',
    calories: 700,
    meal_type: 'fast_food',
    category: 'lunch',
    description: 'Spicy chickpea curry with fried bread',
    carb_g: 85, fat_g: 28, protein_g: 18,
  },
  {
    id: 'biryani',
    name: 'Chicken Biryani (1 plate)',
    emoji: '🍗',
    calories: 750,
    meal_type: 'high_carb',
    category: 'lunch',
    description: 'Spiced rice with marinated chicken',
    carb_g: 100, fat_g: 22, protein_g: 28,
  },
  {
    id: 'veg_biryani',
    name: 'Veg Biryani (1 plate)',
    emoji: '🥘',
    calories: 550,
    meal_type: 'high_carb',
    category: 'lunch',
    description: 'Aromatic basmati rice with vegetables',
    carb_g: 90, fat_g: 12, protein_g: 10,
  },
  {
    id: 'sambar_rice',
    name: 'Sambar Rice',
    emoji: '🍲',
    calories: 400,
    meal_type: 'balanced',
    category: 'lunch',
    description: 'Rice mixed with lentil vegetable stew',
    carb_g: 70, fat_g: 6, protein_g: 12,
  },
  {
    id: 'curd_rice',
    name: 'Curd Rice',
    emoji: '🥛',
    calories: 350,
    meal_type: 'high_protein',
    category: 'lunch',
    description: 'Rice with yogurt, tempering and fruits',
    carb_g: 55, fat_g: 6, protein_g: 12,
  },
  {
    id: 'veg_thali',
    name: 'Full Veg Thali',
    emoji: '🍽️',
    calories: 800,
    meal_type: 'balanced',
    category: 'lunch',
    description: 'Complete meal — dal, sabzi, roti, rice, salad',
    carb_g: 120, fat_g: 20, protein_g: 22,
  },
  // ── DINNER ─────────────────────────────────────────────────
  {
    id: 'roti_dal',
    name: 'Roti + Dal (2 rotis)',
    emoji: '🍽️',
    calories: 450,
    meal_type: 'balanced',
    category: 'dinner',
    description: 'Whole wheat flatbread with lentil soup',
    carb_g: 65, fat_g: 9, protein_g: 15,
  },
  {
    id: 'chicken_curry_rice',
    name: 'Chicken Curry + Rice',
    emoji: '🍗',
    calories: 700,
    meal_type: 'high_protein',
    category: 'dinner',
    description: 'Spicy chicken curry with steamed rice',
    carb_g: 75, fat_g: 20, protein_g: 35,
  },
  {
    id: 'paneer_roti',
    name: 'Paneer Butter Masala + Roti',
    emoji: '🧀',
    calories: 680,
    meal_type: 'balanced',
    category: 'dinner',
    description: 'Cottage cheese in tomato-cream gravy',
    carb_g: 60, fat_g: 32, protein_g: 24,
  },
  {
    id: 'egg_bhurji_toast',
    name: 'Egg Bhurji + Toast',
    emoji: '🍳',
    calories: 380,
    meal_type: 'high_protein',
    category: 'dinner',
    description: 'Spiced scrambled eggs with bread',
    carb_g: 25, fat_g: 18, protein_g: 22,
  },
  {
    id: 'khichdi',
    name: 'Khichdi',
    emoji: '🫕',
    calories: 320,
    meal_type: 'balanced',
    category: 'dinner',
    description: 'Rice and lentil porridge, easy on stomach',
    carb_g: 55, fat_g: 6, protein_g: 12,
  },
  // ── SNACKS ─────────────────────────────────────────────────
  {
    id: 'samosa_2',
    name: 'Samosa (2)',
    emoji: '🥟',
    calories: 280,
    meal_type: 'fast_food',
    category: 'snack',
    description: 'Fried pastry with potato filling',
    carb_g: 38, fat_g: 12, protein_g: 5,
  },
  {
    id: 'vada_pav',
    name: 'Vada Pav',
    emoji: '🍔',
    calories: 290,
    meal_type: 'fast_food',
    category: 'snack',
    description: "Mumbai's street burger with potato fritter",
    carb_g: 42, fat_g: 11, protein_g: 6,
  },
  {
    id: 'bhel_puri',
    name: 'Bhel Puri',
    emoji: '🥗',
    calories: 180,
    meal_type: 'balanced',
    category: 'snack',
    description: 'Puffed rice snack with tamarind chutney',
    carb_g: 35, fat_g: 4, protein_g: 4,
  },
  {
    id: 'banana',
    name: 'Banana (1)',
    emoji: '🍌',
    calories: 90,
    meal_type: 'high_carb',
    category: 'snack',
    carb_g: 23, fat_g: 0.3, protein_g: 1,
  },
  {
    id: 'apple',
    name: 'Apple (1)',
    emoji: '🍎',
    calories: 80,
    meal_type: 'balanced',
    category: 'snack',
    carb_g: 21, fat_g: 0.2, protein_g: 0.4,
  },
  {
    id: 'roasted_chana',
    name: 'Roasted Chana (1 cup)',
    emoji: '🫘',
    calories: 200,
    meal_type: 'high_protein',
    category: 'snack',
    description: 'Roasted chickpeas — high protein, high fiber',
    carb_g: 30, fat_g: 4, protein_g: 10,
  },
  // ── BEVERAGES ──────────────────────────────────────────────
  {
    id: 'chai',
    name: 'Chai (1 cup)',
    emoji: '☕',
    calories: 50,
    meal_type: 'balanced',
    category: 'beverage',
    description: 'Indian spiced milk tea',
    carb_g: 7, fat_g: 1.5, protein_g: 1.5,
  },
  {
    id: 'coffee',
    name: 'Coffee with Milk',
    emoji: '☕',
    calories: 60,
    meal_type: 'balanced',
    category: 'beverage',
    carb_g: 6, fat_g: 2, protein_g: 2,
  },
  {
    id: 'lassi',
    name: 'Sweet Lassi (1 glass)',
    emoji: '🥛',
    calories: 180,
    meal_type: 'balanced',
    category: 'beverage',
    description: 'Yogurt-based cold drink',
    carb_g: 28, fat_g: 4, protein_g: 6,
  },
  {
    id: 'buttermilk',
    name: 'Buttermilk (1 glass)',
    emoji: '🥛',
    calories: 50,
    meal_type: 'high_protein',
    category: 'beverage',
    carb_g: 5, fat_g: 0.5, protein_g: 3,
  },
  {
    id: 'coconut_water',
    name: 'Coconut Water (1 glass)',
    emoji: '🥥',
    calories: 60,
    meal_type: 'balanced',
    category: 'beverage',
    carb_g: 15, fat_g: 0.5, protein_g: 0.5,
  },
  {
    id: 'protein_shake',
    name: 'Protein Shake',
    emoji: '💪',
    calories: 200,
    meal_type: 'high_protein',
    category: 'beverage',
    description: 'Whey protein with milk',
    carb_g: 20, fat_g: 2, protein_g: 25,
  },
];

// Recipe categories for filter UI
export const RECIPE_CATEGORIES = [
  { id: 'all', label: 'All', emoji: '🍽️' },
  { id: 'breakfast', label: 'Breakfast', emoji: '🌅' },
  { id: 'lunch', label: 'Lunch', emoji: '☀️' },
  { id: 'dinner', label: 'Dinner', emoji: '🌙' },
  { id: 'snack', label: 'Snacks', emoji: '🍿' },
  { id: 'beverage', label: 'Drinks', emoji: '🥤' },
] as const;
