# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.12")
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.12...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Biogears::libbiogears_common Biogears::libbiogears_io Biogears::libbiogears_cdm Biogears::libbiogears Biogears::libbiogears_circuit_test)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Biogears::libbiogears_common
add_library(Biogears::libbiogears_common STATIC IMPORTED)

set_target_properties(Biogears::libbiogears_common PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BIOGEARS_COMMON_BUILD_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Biogears::libbiogears_io
add_library(Biogears::libbiogears_io SHARED IMPORTED)

set_target_properties(Biogears::libbiogears_io PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BIOGEARS_IO_PRESENT;\$<\$<BOOL:OFF>:BIOGEARS_IO_EMBED_STATES>;\$<\$<BOOL:OFF>:BIOGEARS_IO_EMBED_TEMPLATES>;\$<\$<BOOL:ON>:BIOGEARS_IO_EMBED_SCENARIOS>;\$<\$<STREQUAL:AMD64,armv7-a>:XSD_NO_EXPORT>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Biogears::libbiogears_common"
)

# Create imported target Biogears::libbiogears_cdm
add_library(Biogears::libbiogears_cdm SHARED IMPORTED)

set_target_properties(Biogears::libbiogears_cdm PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:AMD64,armv7-a>:XSD_NO_EXPORT>"
  INTERFACE_COMPILE_OPTIONS "\$<\$<PLATFORM_ID:Android>:-w>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "CodeSynthesis::XSD;\$<\$<BOOL:OFF>:protobuf::libprotobuf>;Eigen3::Eigen"
)

# Create imported target Biogears::libbiogears
add_library(Biogears::libbiogears SHARED IMPORTED)

set_target_properties(Biogears::libbiogears PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ENABLE_UNIT_TEST_API;BIOGEARS_THROW_READONLY_EXCEPTIONS;BIOGEARS_THROW_NAN_EXCEPTIONS"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen;Biogears::libbiogears_common;Biogears::libbiogears_cdm;Biogears::libbiogears_io"
)

# Create imported target Biogears::libbiogears_circuit_test
add_library(Biogears::libbiogears_circuit_test SHARED IMPORTED)

set_target_properties(Biogears::libbiogears_circuit_test PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "CodeSynthesis::XSD;Eigen3::Eigen;Biogears::libbiogears"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/Biogears-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
